### ISSUE TITLE
Broader pitch

### ISSUE THREAD

**Issue by tychonievich** [cs1501-spatialreasoning/cs1501-spatialreasoning.github.io#2]
I'd encourage a slightly broader pitch. For example, the first paragraph of the syllbaus could be put more inclusively of other disciplines

> Spatial reasoning skills are strongly correlated with success in engineering and computer science, especially that the introductory levels. Sometimes this is due to the spatial nature of the tasks, but more often it is because professors, texts, and peers use diagrams, figures, and spatial terms and ideas to help explain complicated but not intrinsically spatial concepts Thus, many students, who didn’t develop these skills before coming to college, are at a disadvantage. 

This assumes that we want non-CS students in the course, but I assume that is a fine thing to have...

**Comment by rohitmusti** [comment]
All,

I certainly agree. Spatial reasoning is definitely inclusive of all disciplines that involve constructing mental models and transforming them in various ways.

Best,
Rohit Musti

**Comment by isabelalv** [comment]
Ok, sounds good, I will make the change to the Syllabus page and the Welcome page in a moment
