### ISSUE TITLE
Lesson page structure

### ISSUE THREAD

**Issue by isabelalv** [cs1501-spatialreasoning/cs1501-spatialreasoning.github.io#3]
@rohitmusti I noticed you linked the lecture slides directly to the lesson title in the lessons.html file. I was under the impression that we would be creating separate pages with the lesson description and any links (to the slides or other resources) that we need to make available. Have you forgotten this conversation? I would appreciate it if you would run by me structure changes like these.

**Comment by isabelalv** [comment]
Please, by all means, let us decide the something more permanent

**Comment by rohitmusti** [comment]
Ok, we will do when we meet next week. 

Rohit Musti

**Comment by isabelalv** [comment]
it might be too late, we will be meeting the day before classes start. Hopefully we will have posted the first lecture slides by then

**Comment by rohitmusti** [comment]
In that case, if we don’t want to wait until then. Are we ok with just having our lessons link to google sides? We could have any assignments or homework’s at the end of slides. Not much sense duplicating information on the web page and the slides. 

Rohit Musti

**Comment by isabelalv** [comment]
This is ok with me. I looked and it seems like it is possible to have auto-download links in a google slides document if we want the students to be able to download the files directly. I just wanted to have an agreed-upon plan on how we were going to go about this. Thanks
